cluster_run_lib: Catch correct Error in sync_loggers
If a node is unresponsive when we sync_logggers (for instance if it was
rebalanced out immediately before the cluster was killed), then we get
a URLError instead of an HTTPError:
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>

By catching URLError instead we still cover the HTTPError case as
HTTPError is a subclass of URLError.

Change-Id: Ie40c3c5f21e8f03ba537711612d91c91e463c2bf
Reviewed-on: https://review.couchbase.org/c/ns_server/+/189341
Reviewed-by: Timofey Barmin <timofey.barmin@couchbase.com>
Well-Formed: Build Bot <build@couchbase.com>
Tested-by: Peter Searby <peter.searby@couchbase.com>