MB-66020: Report key test results in GET keys API
Examples:

curl -u Administrator \
'http://127.0.0.1:9000/settings/encryptionKeys/9' | jq ".testResults"

// Everything is OK:

{
  "status": "ok",
  "description": "Test passed",
  "missingNodes": [],
  "errorNodes": [],
  "successNodes": [
    "node3.localhost:9003",
    "node2.localhost:9002",
    "node1.localhost:9001",
    "node0.localhost:9000"
  ],
  "datetime": "2025-10-13T17:06:10-07:00"
}

// Something went wrong:

{
  "status": "error",
  "description": "encryption failed: could not encrypt data error:
secrets (code=Unknown): operation error KMS: Encrypt, https response
error StatusCode: 400, RequestID:
7f4df941-515f-4c59-9b29-d60e0f16a1a3, api error
ExpiredTokenException: The security token included in the request is
expired",
  "missingNodes": [],
  "errorNodes": [
    "node0.localhost:9000"
  ],
  "successNodes": [
    "node3.localhost:9003",
    "node2.localhost:9002",
    "node1.localhost:9001"
  ],
  "datetime": "2025-10-13T17:10:12-07:00"
}

// Some nodes did not report results (e.g. they are down):

{
  "status": "unknown",
  "description": "Missing test results for some nodes",
  "missingNodes": [
    "node3.localhost:9003"
  ],
  "errorNodes": [],
  "successNodes": [
    "node2.localhost:9002",
    "node1.localhost:9001",
    "node0.localhost:9000"
  ],
  "datetime": "2025-10-13T17:13:21-07:00"
}

Change-Id: I973d85bc68f2386920a69420f2118bf7b5816801
Reviewed-on: https://review.couchbase.org/c/ns_server/+/235108
Reviewed-by: Navdeep S Boparai <navdeep.boparai@couchbase.com>
Well-Formed: Build Bot <build@couchbase.com>
Tested-by: Timofey Barmin <timofey.barmin@couchbase.com>