MB-61400: [BP] [enacl] Get rid of clang15 compilation errors
This is a backport of MB-61217.

According to erlang doc proper typing for UNLOAD is
void (*unload)(ErlNifEnv* caller_env, void* priv_data)

Error:
enacl_nif.c:430:83: error: incompatible function pointer types
initializing

'void (*)(ErlNifEnv *, void *)'

with an expression of type

'int (ErlNifEnv *, void **, ERL_NIF_TERM)'

Also suppress the "pointer is missing a nullability type specifier"
warnings.

Change-Id: I01329632dbf37efe0d69e66cdce1196ef36306ba
Reviewed-on: https://review.couchbase.org/c/ns_server/+/208058
Well-Formed: Build Bot <build@couchbase.com>
Reviewed-by: Timofey Barmin <timofey.barmin@couchbase.com>
Tested-by: Build Bot <build@couchbase.com>