MB-61292: Don't use dash in encryption at rest audit
... names as it breaks windows build

couchbase_audit_events.h(83):
error C2008: '-': unexpected in macro definition

Change-Id: I1e196ebb1d0229386aeb09c2f675fbcc2e63d74b
Reviewed-on: https://review.couchbase.org/c/ns_server/+/222662
Well-Formed: Build Bot <build@couchbase.com>
Reviewed-by: Navdeep S Boparai <navdeep.boparai@couchbase.com>
Tested-by: Timofey Barmin <timofey.barmin@couchbase.com>